version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=camunda"
      - "POSTGRES_PASSWORD=camunda"
    volumes:
      # Создать в папке .yml файла папку postgres/data
      - ./postgres/data:/var/lib/postgresql/data
    hostname: "db"
    networks:
      - camunda_net
      - db_net

  db-admin:
    image: adminer
    restart: always
    ports:
      - "8080:8081"
    hostname: "db-admin"
    networks:
      - db_net
    depends_on:
      - db
  
  camunda:
    image: camunda/camunda-bpm-platform
    restart: always
    environment:
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URL=jdbc:postgresql://db:5432/process-engine"
      - "DB_USERNAME=camunda"
      - "DB_PASSWORD=camunda"
      - "WAIT_FOR=db:5432"
      - "WAIT_FOR_TIMEOUT=60"
    ports:
      - "8080:8080"
    hostname: "camunda"
    networks:
      - camunda_net
    depends_on:
      - db
    
networks:
  camunda_net:
  db_net:
